/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
        setTitle("Conversor");
        setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCent = new javax.swing.JLabel();
        jTextFieldCent = new javax.swing.JTextField();
        jButtonConvertir = new javax.swing.JButton();
        jLabelCentPul = new javax.swing.JLabel();
        jTextFieldPul = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCent.setText("Centimetros");

        jTextFieldCent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCentFocusLost(evt);
            }
        });
        jTextFieldCent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCentActionPerformed(evt);
            }
        });
        jTextFieldCent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCentKeyPressed(evt);
            }
        });

        jButtonConvertir.setText("Convertir");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        jLabelCentPul.setText("Pulgadas");

        jTextFieldPul.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPulFocusLost(evt);
            }
        });
        jTextFieldPul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPulActionPerformed(evt);
            }
        });
        jTextFieldPul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPulKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCentPul)
                        .addGap(33, 33, 33)
                        .addComponent(jTextFieldPul, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCent)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCent, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConvertir)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCent)
                    .addComponent(jTextFieldCent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConvertir)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCentPul)
                    .addComponent(jTextFieldPul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCentActionPerformed

    //A PULGADAS
    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        // TODO add your handling code here:
        
        if (convertir) {
            convertirAPulgadas();
            
        } 
        else {
            convertirACentimetros();
           
        }
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    private void convertirACentimetros() throws NumberFormatException {
        Double pulgDoble = null;
        try {
        pulgDoble = Double.valueOf(jTextFieldPul.getText().replace(',', '.'));
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar Numeros","Error", JOptionPane.ERROR_MESSAGE );
        }
        Double CentDouble = pulgDoble * UNA_PULGADA;
        jTextFieldCent.setText(String.format("%.2f", CentDouble));
    }

    private void convertirAPulgadas() throws NumberFormatException {
        Double CentDouble= null;
        try {
            CentDouble = Double.valueOf(jTextFieldCent.getText().replace(',', '.'));
                    
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar Numeros","Error", JOptionPane.ERROR_MESSAGE );
        }
        Double pulgDoble = CentDouble / UNA_PULGADA;
        jTextFieldPul.setText(String.format("%.2f", pulgDoble));
        
    }

    private void jTextFieldPulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPulActionPerformed

    private void jTextFieldPulFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPulFocusLost
        // TODO add your handling code here:
        convertir= false;
    }//GEN-LAST:event_jTextFieldPulFocusLost

    private void jTextFieldCentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCentFocusLost
        // TODO add your handling code here:
        convertir= true;
    }//GEN-LAST:event_jTextFieldCentFocusLost

    private void jTextFieldCentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCentKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar()== KeyEvent.VK_ENTER) {
          convertirAPulgadas();            
        }
    }//GEN-LAST:event_jTextFieldCentKeyPressed

    private void jTextFieldPulKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPulKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyChar()== KeyEvent.VK_ENTER) {
          convertirACentimetros();            
        }
    }//GEN-LAST:event_jTextFieldPulKeyPressed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JLabel jLabelCent;
    private javax.swing.JLabel jLabelCentPul;
    private javax.swing.JTextField jTextFieldCent;
    private javax.swing.JTextField jTextFieldPul;
    // End of variables declaration//GEN-END:variables

    private static final double UNA_PULGADA = 2.54;
    private Boolean convertir;
}
